### ISSUE TITLE
yarn run dev后, 如何通过IP访问

### ISSUE THREAD

**Issue by tomtsang** [rootsongjc/cheatsheets#1]
## 环境

**版本和配置信息**

- ruby版本：2.3
- ubuntu：16.04

**说明**

- 腾讯云

**IP** 

- 内网: 172.16.0.12

## 操作

**导致该问题的操作或现象**

依据 [rstacruz's cheatsheets](https://github.com/rstacruz/cheatsheets/blob/master/CONTRIBUTING.md) 提示进行

```bash
yarn install
bundle install
SET PORT=4001
yarn run dev
```
之后, `telnet 127.0.0.1:4001` 能通, 内网与公网 telnet 不通.

防火墙已开4001端口.

## 日志

**日志或报错信息**

```bash
ubuntu@VM-0-12-ubuntu:~$ telnet 127.0.0.1 4001
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Connection closed by foreign host.
ubuntu@VM-0-12-ubuntu:~$ telnet 172.16.0.12 4001
Trying 172.16.0.12...
telnet: Unable to connect to remote host: Connection refused
ubuntu@VM-0-12-ubuntu:~$
```

## 思考与提问

经查, `yarn run dev` 是 运行的 `make dev`, 通过`Makefile`, 知, 运行的是下面部分
```bash
dev-jekyll:
	if [ -f _site ]; then \
		bundle exec jekyll serve --safe --trace --drafts --watch --incremental --port $(PORT); \
		else \
		bundle exec jekyll serve --safe --trace --drafts --watch --port $(PORT); \
		fi
```
那么如何在这`bundle exec jekyll serve`里面绑定IP, 从而使得能够通过 
```bash
wget http://172.16.0.12:4001/ 
```
获取
```bash
wget http://127.0.0.1:4001/ 
```
一样的效果呢?

另问, 这个项目是`yarn run dev`启动形成服务网页的么? 难道我的方式本身就不对?

**Comment by rootsongjc** [comment]
没必要serve，直接生成静态内容即可，然后直接托管在你的腾讯云上。

**Comment by tomtsang** [comment]
好的..那我就直接把文件夹_site/下的内容放上去吧..

如果知道如何绑定IP, 也可以留言给我

同时, 老师有没有考虑过, 出一个简单的使用说明(教程)..比如, 如何新建 md 文件(像 hugo new 这样的命令)

**Comment by tomtsang** [comment]
对了, 超哥, 静态内容, 有点问题... 比如搜索 `bash`, 跳转的话, 是 http://192.168.33.220:8000/bash (这个时候, 会找不到文件) 而不是 http://192.168.33.220:8000/bash.html , 这个是哪里出了问题?

**Comment by rootsongjc** [comment]
本来URL后面就是没有`.html`的啊！跳转到`http://xxx/bash`是正常的啊

**Comment by tomtsang** [comment]
超哥, 生成的静态文件夹是工程下的 `_site` 吧?

**Comment by rootsongjc** [comment]
没错

**Comment by tomtsang** [comment]
超哥, 我明白了, 很可能是: 你 seo 优化去掉html 页面的后缀 `.html` 
然后我做了这个处理后, 也达到了效果.
托管的时候可以优化去掉html 页面的后缀 `.html` , 但是, 本地调试的时候, 呵呵, 就必须手工加`.html`了.
希望有更好的办法, 期待
